[package]
name = "psemu"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield = "0.19"
clap = { version = "4.0", features = ["derive"] }
pixels = "0.15"
psdisasm = "0.1.0"
rustyline = "15.0.0"
winit = "0.30"
